services:
  - type: web
    name: learn-bima-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18
